# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d6d959b6cfbcbf41f434c481940e7fa70dc76bba58bad18f5bbd76eb6e68263e1df138091c12a333b249567ce19602fd589eb2cc7b926a9d0295a226d860a5

test:
  secret_key_base: f46baea511d6d1d1f47867175882a571bb38cb0aad0d2a2ca24b6fcf1214d615a8cf26dbeadbe4104f531788fc419b55f876cc760b3483493b3d38b299e496a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
